//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD_Asp_MVC__JQuery_Ajax_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CityTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CityTable()
        {
            this.EmployeTables = new HashSet<EmployeTable>();
        }
    
        public int CityId { get; set; }
        public string CItyName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeTable> EmployeTables { get; set; }
    }
}
