//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD_Asp_MVC__JQuery_Ajax_.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EmployeManagementEntities : DbContext
    {
        public EmployeManagementEntities()
            : base("name=EmployeManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CityTable> CityTables { get; set; }
        public virtual DbSet<EmployeTable> EmployeTables { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
